{
    "status": "1", 
    "data": {
        "tallymessage": [
            {
                "metadata": {
                    "type": "Voucher", 
                    "remoteid": "130ddfef-7839-4331-b2a2-0b5fbce72f04-00028db6", 
                    "vchkey": "130ddfef-7839-4331-b2a2-0b5fbce72f04-0000b411:00000008", 
                    "vchtype": "Gst Sales E", 
                    "action": "Create", 
                    "objview": "Invoice Voucher View"
                }, 
                "address": [
                    {
                        "metadata": true, 
                        "type": "String"
                    }, 
                    "Tallarevu"
                ], 
                "basicbuyeraddress": [
                    {
                        "metadata": true, 
                        "type": "String"
                    }, 
                    "Tallarevu"
                ], 
                "oldauditentryids": [
                    {
                        "metadata": true, 
                        "type": "Number"
                    }, 
                    "-1"
                ], 
                "date": "20260317", 
                "vchstatusdate": "20260317", 
                "guid": "130ddfef-7839-4331-b2a2-0b5fbce72f04-00028db6", 
                "gstregistrationtype": "Unregistered/Consumer", 
                "vatdealertype": "Regular", 
                "statename": "Andhra Pradesh", 
                "countryofresidence": "India", 
                "placeofsupply": "Andhra Pradesh", 
                "vouchertypename": "Gst Sales E", 
                "classname": "GST", 
                "partyname": "KeshavSoft1", 
                "gstregistration": {
                    "value": "Andhra Pradesh Registration", 
                    "taxtype": "GST", 
                    "taxregistration": "37ABPPN4785P1ZH"
                }, 
                "cmpgstin": "37ABPPN4785P1ZH", 
                "partyledgername": "KeshavSoft1", 
                "vouchernumber": "E/25-26/903", 
                "basicbuyername": "KeshavSoft1", 
                "cmpgstregistrationtype": "Regular", 
                "partymailingname": "KeshavSoft1", 
                "partypincode": "533001", 
                "consigneemailingname": "KeshavSoft1", 
                "consigneepincode": "533001", 
                "consigneestatename": "Andhra Pradesh", 
                "cmpgststate": "Andhra Pradesh", 
                "consigneecountryname": "India", 
                "basicbasepartyname": "KeshavSoft1", 
                "numberingstyle": "Auto Retain", 
                "cstformissuetype": "\u0004 Not Applicable", 
                "cstformrecvtype": "\u0004 Not Applicable", 
                "fbtpaymenttype": "Default", 
                "persistedview": "Invoice Voucher View", 
                "vchstatustaxadjustment": "Default", 
                "vchstatusvouchertype": "Gst Sales E", 
                "vchstatustaxunit": "Andhra Pradesh Registration", 
                "vchgstclass": "\u0004 Not Applicable", 
                "vchentrymode": "Item Invoice", 
                "vouchertypeorigname": "Gst Sales E", 
                "diffactualqty": false, 
                "ismstfromsync": false, 
                "isdeleted": false, 
                "issecurityonwhenentered": false, 
                "asoriginal": false, 
                "audited": false, 
                "iscommonparty": false, 
                "forjobcosting": false, 
                "isoptional": false, 
                "effectivedate": "20260317", 
                "useforexcise": false, 
                "isforjobworkin": false, 
                "allowconsumption": false, 
                "useforinterest": false, 
                "useforgainloss": false, 
                "useforgodowntransfer": false, 
                "useforcompound": false, 
                "useforservicetax": false, 
                "isreversechargeapplicable": false, 
                "issystem": false, 
                "isfetchedonly": false, 
                "isgstoverridden": false, 
                "iscancelled": false, 
                "isonhold": false, 
                "issummary": false, 
                "isecommercesupply": false, 
                "isboenotapplicable": false, 
                "isgstsecsevenapplicable": false, 
                "ignoreeinvvalidation": false, 
                "cmpgstisothterritoryassessee": false, 
                "partygstisothterritoryassessee": false, 
                "irnjsonexported": false, 
                "irncancelled": false, 
                "ignoregstconflictinmig": false, 
                "isopbaltransaction": false, 
                "ignoregstformatvalidation": false, 
                "iseligibleforitc": true, 
                "ignoregstoptionaluncertain": false, 
                "updatesummaryvalues": false, 
                "isewaybillapplicable": false, 
                "isdeletedretained": false, 
                "isnull": false, 
                "isexcisevoucher": false, 
                "excisetaxoverride": false, 
                "usefortaxunittransfer": false, 
                "isexer1nopoverwrite": false, 
                "isexf2nopoverwrite": false, 
                "isexer3nopoverwrite": false, 
                "ignoreposvalidation": false, 
                "exciseopening": false, 
                "useforfinalproduction": false, 
                "istdsoverridden": false, 
                "istcsoverridden": false, 
                "istdstcscashvch": false, 
                "includeadvpymtvch": false, 
                "issubworkscontract": false, 
                "isvatoverridden": false, 
                "ignoreorigvchdate": false, 
                "isvatpaidatcustoms": false, 
                "isdeclaredtocustoms": false, 
                "vatadvancepayment": false, 
                "vatadvpay": false, 
                "iscstdelcaredgoodssales": false, 
                "isvatrestaxinv": false, 
                "isservicetaxoverridden": false, 
                "isisdvoucher": false, 
                "isexciseoverridden": false, 
                "isexcisesupplyvch": false, 
                "gstnotexported": false, 
                "ignoregstinvalidation": false, 
                "isgstrefund": false, 
                "ovrdnewaybillapplicability": false, 
                "isvatprincipalaccount": false, 
                "vchstatusisvchnumused": false, 
                "vchgststatusisincluded": true, 
                "vchgststatusisuncertain": false, 
                "vchgststatusisexcluded": false, 
                "vchgststatusisapplicable": true, 
                "vchgststatusisgstr2breconciled": false, 
                "vchgststatusisgstr2bonlyinportal": false, 
                "vchgststatusisgstr2bonlyinbooks": false, 
                "vchgststatusisgstr2bmismatch": false, 
                "vchgststatusisgstr2bindiffperiod": false, 
                "vchgststatusisreteffdateoverrdn": false, 
                "vchgststatusisoverrdn": false, 
                "vchgststatusisstatindiffdate": false, 
                "vchgststatusisretindiffdate": false, 
                "vchgststatusmainsectionexcluded": false, 
                "vchgststatusisbranchtransferout": false, 
                "vchgststatusissystemsummary": false, 
                "vchstatusisunregisteredrcm": false, 
                "vchstatusisoptional": false, 
                "vchstatusiscancelled": false, 
                "vchstatusisdeleted": false, 
                "vchstatusisopeningbalance": false, 
                "vchstatusisfetchedonly": false, 
                "vchgststatusisoptionaluncertain": false, 
                "vchstatusisreacceptforhsndone": false, 
                "vchstatusisreaccephsnsixonedone": true, 
                "paymentlinkhasmultiref": false, 
                "isshippingwithinstate": false, 
                "isoverseastouristtrans": false, 
                "isdesignatedzoneparty": false, 
                "hascashflow": false, 
                "ispostdated": false, 
                "usetrackingnumber": false, 
                "isinvoice": true, 
                "mfgjournal": false, 
                "hasdiscounts": false, 
                "aspayslip": false, 
                "iscostcentre": false, 
                "isstxnonrealizedvch": false, 
                "isexcisemanufactureron": false, 
                "isblankcheque": false, 
                "isvoid": false, 
                "orderlinestatus": false, 
                "vatisagnstcancsales": false, 
                "vatispurcexempted": false, 
                "isvatrestaxinvoice": false, 
                "vatisassesablecalcvch": false, 
                "isvatdutypaid": true, 
                "isdeliverysameasconsignee": false, 
                "isdispatchsameasconsignor": false, 
                "isdeletedvchretained": false, 
                "vchonlyaddlinfoupdated": false, 
                "changevchmode": false, 
                "resetirnqrcode": false, 
                "errkey": "0", 
                "alterid": " 230122", 
                "masterid": " 167350", 
                "qrcodecrc": "0", 
                "exchangeactivityid": "0", 
                "voucherkey": "197985107443720", 
                "voucherretainkey": "7809", 
                "ecfeerate": "0", 
                "vatconsignmentno": "0", 
                "vatrateoftax": "0", 
                "eidiscountrate": "0", 
                "wbtransferassessrate": "0", 
                "vatwcdeductionperc": "0", 
                "isgstovrdncrc": "0", 
                "igngstfmtcrc": "0", 
                "igneinvvalidcrc": "0", 
                "ignextnvalidcrc": "0", 
                "ignpartbvalidcrc": "0", 
                "igntransidvalidcrc": "0", 
                "igngenerationvalidcrc": "0", 
                "igngstvalidcrc": "0", 
                "igngstoptuncertcrc": "0", 
                "rateofinvoicetax": "0", 
                "vchstatusdummylong": "0", 
                "vattdsrate": "0", 
                "reuseholeid": "0", 
                "vouchernumberseries": "Default", 
                "updateddatetime": "000000000", 
                "irnackupdatedatetime": "000000000", 
                "eidefaultled_classrate": "0", 
                "eidefaultled_classaddlrate": "0", 
                "tempconsignorpincodenumber": "0", 
                "tempgstewaypincodenumber": "0", 
                "tempgstewayconspincodenumber": "0", 
                "tempconsigneepincodenumber": "0", 
                "tempgstewaydistance": "0", 
                "allinventoryentries": [
                    {
                        "stockitemname": "Coke-Mts-5%", 
                        "gstovrdnisrevchargeappl": "\u0004 Not Applicable", 
                        "gstovrdntaxability": "Taxable", 
                        "gstsourcetype": "Stock Item", 
                        "gstitemsource": "Coke-Mts-5%", 
                        "hsnsourcetype": "Stock Item", 
                        "hsnitemsource": "Coke-Mts-5%", 
                        "gstovrdntypeofsupply": "Goods", 
                        "gstrateinferapplicability": "As per Masters/Company", 
                        "gsthsnname": "540720", 
                        "gsthsndescription": "Woven Fabric", 
                        "gsthsninferapplicability": "As per Masters/Company", 
                        "isdeemedpositive": false, 
                        "isgstassessablevalueoverridden": false, 
                        "strdisgstapplicable": false, 
                        "contentnegispos": false, 
                        "islastdeemedpositive": false, 
                        "isautonegate": false, 
                        "iscustomsclearance": false, 
                        "istrackcomponent": false, 
                        "istrackproduction": false, 
                        "isprimaryitem": false, 
                        "isscrap": false, 
                        "rate": "100.00/Mts", 
                        "discount": "0", 
                        "vattaxrate": "0", 
                        "originvgoodsqty": "0", 
                        "excisemrpabatement": "0", 
                        "addlcostperc": "0", 
                        "revisedrateofduty": "0", 
                        "origrateofduty": "0", 
                        "origmrpabatement": "0", 
                        "excisereturndutyrate": "0", 
                        "gvatexciserate": "0", 
                        "amount": "100.00", 
                        "actualqty": " 1.00 Mts", 
                        "billedqty": " 1.00 Mts", 
                        "mrprate": "105.00/Mts", 
                        "inclvatrate": "105.00/Mts", 
                        "tempgstcgstrate": "0", 
                        "tempgstsgstrate": "0", 
                        "tempgstigstrate": "0", 
                        "tempgststatecessrate": "0", 
                        "tempgstcessrate": "0", 
                        "tempgstcessqtyrate": "0", 
                        "temprate": "0", 
                        "tempvatclsfnrate": "0", 
                        "batchallocations": [
                            {
                                "godownname": "Main Location", 
                                "batchname": "Primary Batch", 
                                "indentno": "\u0004 Not Applicable", 
                                "orderno": "\u0004 Not Applicable", 
                                "trackingnumber": "\u0004 Not Applicable", 
                                "dynamiccstiscleared": false, 
                                "amount": "100.00", 
                                "actualqty": " 1.00 Mts", 
                                "billedqty": " 1.00 Mts", 
                                "costtrackid": "0"
                            }
                        ], 
                        "accountingallocations": [
                            {
                                "oldauditentryids": [
                                    {
                                        "metadata": true, 
                                        "type": "Number"
                                    }, 
                                    "-1"
                                ], 
                                "ledgername": "GST SALES", 
                                "classrate": "100.00", 
                                "gstclass": "\u0004 Not Applicable", 
                                "isdeemedpositive": false, 
                                "ledgerfromitem": false, 
                                "removezeroentries": false, 
                                "ispartyledger": false, 
                                "gstoverridden": false, 
                                "isgstassessablevalueoverridden": false, 
                                "strdisgstapplicable": false, 
                                "strdgstispartyledger": false, 
                                "strdgstisdutyledger": false, 
                                "contentnegispos": false, 
                                "islastdeemedpositive": false, 
                                "iscapvattaxaltered": false, 
                                "iscapvatnotclaimed": false, 
                                "stcradjpercent": "0", 
                                "roundlimit": "0", 
                                "rateofaddlvat": "0", 
                                "rateofcessonvat": "0", 
                                "vattaxrate": "0", 
                                "vatitemqty": "0", 
                                "vatwcdeductrate": "0", 
                                "previnvtotalnum": "0", 
                                "vatwcdeductionrate": "0", 
                                "gsttaxrate": "0", 
                                "originvgoodsqty": "0", 
                                "capvattaxrate": "0", 
                                "amount": "100.00", 
                                "tempgstcgstrate": "0", 
                                "tempgstsgstrate": "0", 
                                "tempgstigstrate": "0", 
                                "tempgststatecessrate": "0", 
                                "tempgstcessrate": "0", 
                                "tempgstcessqtyrate": "0", 
                                "denominationcount2000x": "0", 
                                "denominationcount1000x": "0", 
                                "denominationcount500x": "0", 
                                "denominationcount200x": "0", 
                                "denominationcount100x": "0", 
                                "denominationcount50x": "0", 
                                "denominationcount20x": "0", 
                                "denominationcount10x": "0", 
                                "denominationcount5x": "0", 
                                "denominationcount2x": "0", 
                                "denominationcount1x": "0", 
                                "vatassesmentate": "0"
                            }
                        ], 
                        "ratedetails": [
                            {
                                "gstratedutyhead": "CGST", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": " 2.50", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "SGST/UTGST", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": " 2.50", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "IGST", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": " 5", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "Cess", 
                                "gstratevaluationtype": "\u0004 Not Applicable", 
                                "gstrate": "0", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "State Cess", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": "0", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }
                        ]
                    }, 
                    {
                        "stockitemname": "Basins-Nos-3924-18%", 
                        "gstovrdnisrevchargeappl": "\u0004 Not Applicable", 
                        "gstovrdntaxability": "Taxable", 
                        "gstsourcetype": "Stock Item", 
                        "gstitemsource": "Basins-Nos-3924-18%", 
                        "hsnsourcetype": "Stock Item", 
                        "hsnitemsource": "Basins-Nos-3924-18%", 
                        "gstovrdntypeofsupply": "Goods", 
                        "gstrateinferapplicability": "As per Masters/Company", 
                        "gsthsnname": "39241090", 
                        "gsthsndescription": "Plastic Basins", 
                        "gsthsninferapplicability": "As per Masters/Company", 
                        "isdeemedpositive": false, 
                        "isgstassessablevalueoverridden": false, 
                        "strdisgstapplicable": false, 
                        "contentnegispos": false, 
                        "islastdeemedpositive": false, 
                        "isautonegate": false, 
                        "iscustomsclearance": false, 
                        "istrackcomponent": false, 
                        "istrackproduction": false, 
                        "isprimaryitem": false, 
                        "isscrap": false, 
                        "rate": "200.00/Nos", 
                        "discount": "0", 
                        "vattaxrate": "0", 
                        "originvgoodsqty": "0", 
                        "excisemrpabatement": "0", 
                        "addlcostperc": "0", 
                        "revisedrateofduty": "0", 
                        "origrateofduty": "0", 
                        "origmrpabatement": "0", 
                        "excisereturndutyrate": "0", 
                        "gvatexciserate": "0", 
                        "amount": "400.00", 
                        "actualqty": " 2 Nos", 
                        "billedqty": " 2 Nos", 
                        "mrprate": "236.00/Nos", 
                        "inclvatrate": "236.00/Nos", 
                        "tempgstcgstrate": "0", 
                        "tempgstsgstrate": "0", 
                        "tempgstigstrate": "0", 
                        "tempgststatecessrate": "0", 
                        "tempgstcessrate": "0", 
                        "tempgstcessqtyrate": "0", 
                        "temprate": "0", 
                        "tempvatclsfnrate": "0", 
                        "batchallocations": [
                            {
                                "godownname": "Main Location", 
                                "batchname": "Primary Batch", 
                                "indentno": "\u0004 Not Applicable", 
                                "orderno": "\u0004 Not Applicable", 
                                "trackingnumber": "\u0004 Not Applicable", 
                                "dynamiccstiscleared": false, 
                                "amount": "400.00", 
                                "actualqty": " 2 Nos", 
                                "billedqty": " 2 Nos", 
                                "costtrackid": "0"
                            }
                        ], 
                        "accountingallocations": [
                            {
                                "oldauditentryids": [
                                    {
                                        "metadata": true, 
                                        "type": "Number"
                                    }, 
                                    "-1"
                                ], 
                                "ledgername": "GST SALES", 
                                "classrate": "200.00", 
                                "gstclass": "\u0004 Not Applicable", 
                                "isdeemedpositive": false, 
                                "ledgerfromitem": false, 
                                "removezeroentries": false, 
                                "ispartyledger": false, 
                                "gstoverridden": false, 
                                "isgstassessablevalueoverridden": false, 
                                "strdisgstapplicable": false, 
                                "strdgstispartyledger": false, 
                                "strdgstisdutyledger": false, 
                                "contentnegispos": false, 
                                "islastdeemedpositive": false, 
                                "iscapvattaxaltered": false, 
                                "iscapvatnotclaimed": false, 
                                "stcradjpercent": "0", 
                                "roundlimit": "0", 
                                "rateofaddlvat": "0", 
                                "rateofcessonvat": "0", 
                                "vattaxrate": "0", 
                                "vatitemqty": "0", 
                                "vatwcdeductrate": "0", 
                                "previnvtotalnum": "0", 
                                "vatwcdeductionrate": "0", 
                                "gsttaxrate": "0", 
                                "originvgoodsqty": "0", 
                                "capvattaxrate": "0", 
                                "amount": "400.00", 
                                "tempgstcgstrate": "0", 
                                "tempgstsgstrate": "0", 
                                "tempgstigstrate": "0", 
                                "tempgststatecessrate": "0", 
                                "tempgstcessrate": "0", 
                                "tempgstcessqtyrate": "0", 
                                "denominationcount2000x": "0", 
                                "denominationcount1000x": "0", 
                                "denominationcount500x": "0", 
                                "denominationcount200x": "0", 
                                "denominationcount100x": "0", 
                                "denominationcount50x": "0", 
                                "denominationcount20x": "0", 
                                "denominationcount10x": "0", 
                                "denominationcount5x": "0", 
                                "denominationcount2x": "0", 
                                "denominationcount1x": "0", 
                                "vatassesmentate": "0"
                            }
                        ], 
                        "ratedetails": [
                            {
                                "gstratedutyhead": "CGST", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": " 9", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "SGST/UTGST", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": " 9", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "IGST", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": " 18", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "Cess", 
                                "gstratevaluationtype": "\u0004 Not Applicable", 
                                "gstrate": "0", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }, 
                            {
                                "gstratedutyhead": "State Cess", 
                                "gstratevaluationtype": "Based on Value", 
                                "gstrate": "0", 
                                "gstrateperunit": "0", 
                                "tempgstrate": "0"
                            }
                        ]
                    }
                ], 
                "ledgerentries": [
                    {
                        "oldauditentryids": [
                            {
                                "metadata": true, 
                                "type": "Number"
                            }, 
                            "-1"
                        ], 
                        "roundtype": "\u0004 Not Applicable", 
                        "ledgername": "KeshavSoft1", 
                        "methodtype": "GST", 
                        "gstclass": "\u0004 Not Applicable", 
                        "isdeemedpositive": true, 
                        "ledgerfromitem": false, 
                        "removezeroentries": true, 
                        "ispartyledger": true, 
                        "gstoverridden": false, 
                        "isgstassessablevalueoverridden": false, 
                        "strdisgstapplicable": false, 
                        "strdgstispartyledger": false, 
                        "strdgstisdutyledger": false, 
                        "contentnegispos": false, 
                        "islastdeemedpositive": true, 
                        "iscapvattaxaltered": false, 
                        "iscapvatnotclaimed": false, 
                        "stcradjpercent": "0", 
                        "roundlimit": "0", 
                        "rateofaddlvat": "0", 
                        "rateofcessonvat": "0", 
                        "vattaxrate": "0", 
                        "vatitemqty": "0", 
                        "vatwcdeductrate": "0", 
                        "previnvtotalnum": "0", 
                        "vatwcdeductionrate": "0", 
                        "gsttaxrate": "0", 
                        "originvgoodsqty": "0", 
                        "capvattaxrate": "0", 
                        "amount": "-577.00", 
                        "vatexpamount": "-90.00", 
                        "tempgstcgstrate": "0", 
                        "tempgstsgstrate": "0", 
                        "tempgstigstrate": "0", 
                        "tempgststatecessrate": "0", 
                        "tempgstcessrate": "0", 
                        "tempgstcessqtyrate": "0", 
                        "denominationcount2000x": "0", 
                        "denominationcount1000x": "0", 
                        "denominationcount500x": "0", 
                        "denominationcount200x": "0", 
                        "denominationcount100x": "0", 
                        "denominationcount50x": "0", 
                        "denominationcount20x": "0", 
                        "denominationcount10x": "0", 
                        "denominationcount5x": "0", 
                        "denominationcount2x": "0", 
                        "denominationcount1x": "0", 
                        "vatassesmentate": "0", 
                        "billallocations": [
                            {
                                "name": "E/25-26/903", 
                                "billtype": "New Ref", 
                                "tdsdeducteeisspecialrate": false, 
                                "tdsdeducteespecialrate": "0", 
                                "amount": "-577.00"
                            }
                        ]
                    }, 
                    {
                        "oldauditentryids": [
                            {
                                "metadata": true, 
                                "type": "Number"
                            }, 
                            "-1"
                        ], 
                        "roundtype": "\u0004 Not Applicable", 
                        "ledgername": "CGST Output", 
                        "methodtype": "GST", 
                        "gstclass": "\u0004 Not Applicable", 
                        "isdeemedpositive": false, 
                        "ledgerfromitem": false, 
                        "removezeroentries": true, 
                        "ispartyledger": false, 
                        "gstoverridden": false, 
                        "isgstassessablevalueoverridden": false, 
                        "strdisgstapplicable": false, 
                        "strdgstispartyledger": false, 
                        "strdgstisdutyledger": false, 
                        "contentnegispos": false, 
                        "islastdeemedpositive": false, 
                        "iscapvattaxaltered": false, 
                        "iscapvatnotclaimed": false, 
                        "stcradjpercent": "0", 
                        "roundlimit": "0", 
                        "rateofaddlvat": "0", 
                        "rateofcessonvat": "0", 
                        "vattaxrate": "0", 
                        "vatitemqty": "0", 
                        "vatwcdeductrate": "0", 
                        "previnvtotalnum": "0", 
                        "vatwcdeductionrate": "0", 
                        "gsttaxrate": "0", 
                        "originvgoodsqty": "0", 
                        "capvattaxrate": "0", 
                        "amount": "38.50", 
                        "vatexpamount": "90.00", 
                        "tempgstcgstrate": "0", 
                        "tempgstsgstrate": "0", 
                        "tempgstigstrate": "0", 
                        "tempgststatecessrate": "0", 
                        "tempgstcessrate": "0", 
                        "tempgstcessqtyrate": "0", 
                        "denominationcount2000x": "0", 
                        "denominationcount1000x": "0", 
                        "denominationcount500x": "0", 
                        "denominationcount200x": "0", 
                        "denominationcount100x": "0", 
                        "denominationcount50x": "0", 
                        "denominationcount20x": "0", 
                        "denominationcount10x": "0", 
                        "denominationcount5x": "0", 
                        "denominationcount2x": "0", 
                        "denominationcount1x": "0", 
                        "vatassesmentate": "0"
                    }, 
                    {
                        "oldauditentryids": [
                            {
                                "metadata": true, 
                                "type": "Number"
                            }, 
                            "-1"
                        ], 
                        "roundtype": "\u0004 Not Applicable", 
                        "ledgername": "SGST Output", 
                        "methodtype": "GST", 
                        "gstclass": "\u0004 Not Applicable", 
                        "isdeemedpositive": false, 
                        "ledgerfromitem": false, 
                        "removezeroentries": true, 
                        "ispartyledger": false, 
                        "gstoverridden": false, 
                        "isgstassessablevalueoverridden": false, 
                        "strdisgstapplicable": false, 
                        "strdgstispartyledger": false, 
                        "strdgstisdutyledger": false, 
                        "contentnegispos": false, 
                        "islastdeemedpositive": false, 
                        "iscapvattaxaltered": false, 
                        "iscapvatnotclaimed": false, 
                        "stcradjpercent": "0", 
                        "roundlimit": "0", 
                        "rateofaddlvat": "0", 
                        "rateofcessonvat": "0", 
                        "vattaxrate": "0", 
                        "vatitemqty": "0", 
                        "vatwcdeductrate": "0", 
                        "previnvtotalnum": "0", 
                        "vatwcdeductionrate": "0", 
                        "gsttaxrate": "0", 
                        "originvgoodsqty": "0", 
                        "capvattaxrate": "0", 
                        "amount": "38.50", 
                        "vatexpamount": "90.00", 
                        "tempgstcgstrate": "0", 
                        "tempgstsgstrate": "0", 
                        "tempgstigstrate": "0", 
                        "tempgststatecessrate": "0", 
                        "tempgstcessrate": "0", 
                        "tempgstcessqtyrate": "0", 
                        "denominationcount2000x": "0", 
                        "denominationcount1000x": "0", 
                        "denominationcount500x": "0", 
                        "denominationcount200x": "0", 
                        "denominationcount100x": "0", 
                        "denominationcount50x": "0", 
                        "denominationcount20x": "0", 
                        "denominationcount10x": "0", 
                        "denominationcount5x": "0", 
                        "denominationcount2x": "0", 
                        "denominationcount1x": "0", 
                        "vatassesmentate": "0"
                    }
                ], 
                "gst": [
                    {
                        "purposetype": "GST", 
                        "stat": [
                            {
                                "purposetype": "GST", 
                                "statkey": "\u0004 Auto Stat Number", 
                                "isfetchedonly": false, 
                                "isdeleted": false, 
                                "tallycontentuser": [
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
}