POST http://localhost:9000
Content-Type: application/json
TallyRequest: Export
Type: Object
Id: StockItem
SubType: "130ddfef-7839-4331-b2a2-0b5fbce72f04-000044c8"

{
    "static_variables": [
        {
            "name": "svExportFormat",
            "value": "jsonex"
        },
        {
            "name": "svCurrentCompany",
            "value": "Mani9"
        }
    ],
  "fetch_list": [
  "Name",
  "Parent",
  "Category",
  "BaseUnits"
]
}
